on:
  push:
    branches: [ master ]

jobs:
  docker-build:
    runs-on: macos-14

    steps:
      - name: checkout qsc repo
        uses: actions/checkout@v4
        with:
          repository: dolphin-emu/qsc
          path: qsc
      
      - name: checkout build repo
        uses: actions/checkout@v4
        with:
          path: build

      - name: venv setup
        run: |
          python3 -m venv ./venv
          source ./venv/bin/activate
          python3 -m pip install -r qsc/requirements.txt

      - name: build
        run: |
          source ./venv/bin/activate
          cd qsc
          python3 -m qsc ../build/dolphin.yml
      
      - uses: actions/upload-artifact@v4
        with:
          name: qt-build
          path: qsc/dist